const timetables = [
  {
    userId: "d47ffe3f-3b5a-430c-88a5-d4bcf4c875f1",
    timetable: [
      {
        id: "class-1",
        name: "Math 101",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
        day: "Monday",
        category: "class",
      },
      {
        id: "class-2",
        name: "History 202",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
        day: "Tuesday",
        category: "class",
      },
      {
        id: "class-3",
        name: "Physics 301",
        startTime: "11:00 AM",
        endTime: "12:00 PM",
        day: "Monday",
        category: "class",
      },
      {
        id: "class-4",
        name: "Philosophy 101",
        startTime: "12:00 PM",
        endTime: "1:00 PM",
        day: "Wednesday",
        category: "class",
      },
      {
        id: "class-5",
        name: "Computer Science 305",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
        day: "Thursday",
        category: "class",
      },
      {
        id: "study-1",
        name: "Math Study Group",
        startTime: "2:00 PM",
        endTime: "3:00 PM",
        day: "Wednesday",
        category: "study",
      },
      {
        id: "class-6",
        name: "Chemistry 202",
        startTime: "3:00 PM",
        endTime: "4:00 PM",
        day: "Monday",
        category: "class",
      },
      {
        id: "class-7",
        name: "Art History",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
        day: "Tuesday",
        category: "class",
      },
      {
        id: "extracurricular-1",
        name: "Basketball Practice",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
        day: "Thursday",
        category: "extracurricular",
      },
      {
        id: "extracurricular-2",
        name: "Football Practice",
        startTime: "5:00 PM",
        endTime: "6:00 PM",
        day: "Friday",
        category: "extracurricular",
      },
      {
        id: "class-8",
        name: "Economics 101",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
        day: "Wednesday",
        category: "class",
      },
      {
        id: "class-9",
        name: "Psychology 102",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
        day: "Monday",
        category: "class",
      },
      {
        id: "class-10",
        name: "Biology 202",
        startTime: "11:00 AM",
        endTime: "12:00 PM",
        day: "Friday",
        category: "class",
      },
      {
        id: "class-11",
        name: "Literature 201",
        startTime: "12:00 PM",
        endTime: "1:00 PM",
        day: "Thursday",
        category: "class",
      },
      {
        id: "extracurricular-3",
        name: "Drama Club",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
        day: "Friday",
        category: "extracurricular",
      },
      {
        id: "study-2",
        name: "Physics Study Session",
        startTime: "2:00 PM",
        endTime: "3:00 PM",
        day: "Monday",
        category: "study",
      },
      {
        id: "extracurricular-4",
        name: "Music Rehearsal",
        startTime: "3:00 PM",
        endTime: "4:00 PM",
        day: "Wednesday",
        category: "extracurricular",
      },
      {
        id: "extracurricular-5",
        name: "Debate Club",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
        day: "Tuesday",
        category: "extracurricular",
      },
      {
        id: "class-12",
        name: "History 204",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
        day: "Thursday",
        category: "class",
      },
      {
        id: "class-13",
        name: "Geography 101",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
        day: "Friday",
        category: "class",
      },
      {
        id: "study-3",
        name: "Chemistry Study Group",
        startTime: "11:00 AM",
        endTime: "12:00 PM",
        day: "Tuesday",
        category: "study",
      },
      {
        id: "extracurricular-6",
        name: "Swimming Practice",
        startTime: "12:00 PM",
        endTime: "1:00 PM",
        day: "Monday",
        category: "extracurricular",
      },
      {
        id: "class-14",
        name: "Law 101",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
        day: "Tuesday",
        category: "class",
      },
      {
        id: "class-15",
        name: "Sociology 202",
        startTime: "2:00 PM",
        endTime: "3:00 PM",
        day: "Thursday",
        category: "class",
      },
      {
        id: "class-16",
        name: "Anthropology 101",
        startTime: "3:00 PM",
        endTime: "4:00 PM",
        day: "Friday",
        category: "class",
      },
      {
        id: "extracurricular-7",
        name: "Volleyball Practice",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
        day: "Wednesday",
        category: "extracurricular",
      },
    ],
  },
];

export { timetables };
